#!/usr/bin/env python

import os
import sys
import threading
import atexit

from classes import RequestHandler,Server

PORT = 64720 # hex:fcd0

if __name__ == "__main__":
    server = Server(("localhost", PORT), RequestHandler)
    thread = threading.Thread(target=server.serve_forever)
    thread.start()

    atexit.register(lambda: server.shutdown())
    #todo also properly shutdown all sockets
