#ifndef SHARED_H
#define SHARED_H

#define NET_SERVER_PORT 8856
#define NET_MAX_PEERS 8
#define MAX_ADDR_LENGTH 50
#define MAX_MSG_SIZE 1024*1024
#define MAX_CTYPE_IN_USE 10
#define MAX_MEMPOOL_SIZE 50

#endif /* SHARED_H */

